//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_commerceMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        public int Product_ID { get; set; }
        public int Brand_ID { get; set; }
        public string Product_Info { get; set; }
        public string Product_Color { get; set; }
        public Nullable<int> Product_CategoryID { get; set; }
        public Nullable<decimal> Product_Price { get; set; }
        public Nullable<int> Stock { get; set; }
        public string Product_Size { get; set; }
        public double Rating { get; set; }
        public int Product_Sex_ID { get; set; }
        public Nullable<int> Total_Sold { get; set; }
        public string Image_Path { get; set; }
        public string Product_Kid { get; set; }
    
        public virtual Product_Sex Product_Sex { get; set; }
        public virtual tbl_Brand tbl_Brand { get; set; }
        public virtual tbl_Category tbl_Category { get; set; }
    }
}
