//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_commerceMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_User
    {
        public int User_ID { get; set; }
        public string User_Name { get; set; }
        public string User_Surname { get; set; }
        public string User_Mail { get; set; }
        public string User_Password { get; set; }
        public string User_Address { get; set; }
        public Nullable<int> Sex_ID { get; set; }
        public Nullable<int> User_Phone { get; set; }
    }
}
