//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_commerceMVC.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sex
    {
        public int Product_Sex_ID { get; set; }
        public string Sex_Text { get; set; }
    }
}
